# Generated by Django 4.1.5 on 2023-01-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.TextField(blank=True, verbose_name='Заголовок')),
                ('title2', models.TextField(blank=True, verbose_name='Заголовок таблицы 1')),
                ('table1', models.TextField(blank=True, verbose_name='Таблица 1')),
                ('title3', models.TextField(blank=True, verbose_name='Заголовок таблицы 2')),
                ('table2', models.TextField(blank=True, verbose_name='Таблица 2')),
                ('title4', models.TextField(blank=True, verbose_name='Заголовок таблицы 3')),
                ('table3', models.TextField(blank=True, verbose_name='Таблица 3')),
                ('img1', models.ImageField(blank=True, upload_to='img/', verbose_name='1 график сравнения')),
                ('img2', models.ImageField(blank=True, upload_to='img/', verbose_name='2 график сравнения')),
                ('img3', models.ImageField(blank=True, upload_to='img/', verbose_name='3 график сравнения')),
            ],
            options={
                'verbose_name': 'Востребованность',
                'verbose_name_plural': 'Востребованность',
            },
        ),
        migrations.CreateModel(
            name='Geography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, verbose_name='Таблицы')),
                ('first_title', models.CharField(blank=True, max_length=50, verbose_name='Заголовок для 1 фото')),
                ('img1', models.ImageField(blank=True, upload_to='img/', verbose_name='график 1')),
                ('second_title', models.CharField(blank=True, max_length=50, verbose_name='Заголовок для 2 фото')),
                ('img2', models.ImageField(blank=True, upload_to='img/', verbose_name='график 2')),
            ],
            options={
                'verbose_name': 'География',
                'verbose_name_plural': 'География',
            },
        ),
        migrations.CreateModel(
            name='lastVacancyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, verbose_name='Описание профессии')),
                ('img', models.ImageField(blank=True, upload_to='img/', verbose_name='картинка')),
            ],
            options={
                'verbose_name': 'Главная',
                'verbose_name_plural': 'Главные',
            },
        ),
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='img/', verbose_name='Логотип')),
                ('logo_text', models.TextField(max_length=100, verbose_name='Название')),
                ('menu_el_1', models.TextField(max_length=25, verbose_name='1 пункт меню')),
                ('menu_el_2', models.TextField(max_length=25, verbose_name='2 пункт меню')),
                ('menu_el_3', models.TextField(max_length=25, verbose_name='3 пункт меню')),
                ('menu_el_4', models.TextField(max_length=25, verbose_name='4 пункт меню')),
                ('menu_el_5', models.TextField(max_length=25, verbose_name='5 пункт меню')),
                ('author', models.TextField(max_length=50, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Навигация',
                'verbose_name_plural': 'Навигации',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_title', models.CharField(blank=True, max_length=50, verbose_name='Заголовок для таблицы')),
                ('content', models.TextField(blank=True, verbose_name='Таблица')),
                ('img1', models.ImageField(blank=True, upload_to='img/', verbose_name='График 1')),
                ('img2', models.ImageField(blank=True, upload_to='img/', verbose_name='График 2')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
            },
        ),
    ]
