# Generated by Django 4.1.5 on 2023-01-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.TextField(blank=True, verbose_name='Заголовок')),
                ('title2', models.TextField(blank=True, verbose_name='Заголовок таблицы 1')),
                ('table1', models.TextField(blank=True, verbose_name='Таблица 1')),
                ('title3', models.TextField(blank=True, verbose_name='Заголовок таблицы 2')),
                ('table2', models.TextField(blank=True, verbose_name='Таблица 2')),
                ('title4', models.TextField(blank=True, verbose_name='Заголовок таблицы 3')),
                ('table3', models.TextField(blank=True, verbose_name='Таблица 3')),
                ('photo1', models.ImageField(upload_to='media/', verbose_name='Первый график сравнения')),
                ('photo2', models.ImageField(upload_to='media/', verbose_name='Второй график сравнения')),
                ('photo3', models.ImageField(blank=True, upload_to='media/', verbose_name='Третий график сравнения')),
            ],
            options={
                'verbose_name': 'Востребованность',
                'verbose_name_plural': 'Востребованность',
            },
        ),
        migrations.CreateModel(
            name='Geography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, verbose_name='Таблицы')),
                ('first_title', models.CharField(blank=True, max_length=50, verbose_name='Заголовок для первого фото')),
                ('photo1', models.ImageField(upload_to='media/', verbose_name='Первое фото')),
                ('second_title', models.CharField(blank=True, max_length=50, verbose_name='Заголовок для второго фото')),
                ('photo2', models.ImageField(upload_to='media/', verbose_name='Второй график')),
            ],
            options={
                'verbose_name': 'География',
                'verbose_name_plural': 'География',
            },
        ),
        migrations.CreateModel(
            name='lastVacancyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, verbose_name='Описание профессии')),
                ('photo', models.ImageField(upload_to='media/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Главная',
                'verbose_name_plural': 'Главные',
            },
        ),
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='media/', verbose_name='Логотип')),
                ('logo_text', models.TextField(max_length=100, verbose_name='Название')),
                ('first_menu', models.TextField(max_length=25, verbose_name='Первый пункт меню')),
                ('second_menu', models.TextField(max_length=25, verbose_name='Второй пункт меню')),
                ('thierd_menu', models.TextField(max_length=25, verbose_name='Третий пункт меню')),
                ('fourth_menu', models.TextField(max_length=25, verbose_name='Четвертый пункт меню')),
                ('fifth_menu', models.TextField(max_length=25, verbose_name='Пятый пункт меню')),
                ('author', models.TextField(max_length=50, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Навигация',
                'verbose_name_plural': 'Навигации',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_title', models.CharField(blank=True, max_length=50, verbose_name='Заголовок для таблицы')),
                ('content', models.TextField(blank=True, verbose_name='Таблица')),
                ('graph', models.ImageField(upload_to='media/', verbose_name='График 1')),
                ('graph2', models.ImageField(upload_to='media/', verbose_name='График 2')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
            },
        ),
    ]
